#!/bin/bash


cd /tmp/rom


. build/envsetup.sh


lunch aosp_r5x-userdebug
export SELINUX_IGNORE_NEVERALLOWS=true
export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z
ccache -c

mka api-stubs-docs
mka system-api-stubs-docs
mka hiddenapi-lists-docs
mka test-api-stubs-docs

mka bacon -j16 &

sleep 80m
kill %1
ccache -s

