#!/bin/bash

url=https://not.zomenaro69.workers.dev/0:/VApqc.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50 || time aria2c $url -x16 -s50
echo "dl done"
time tar xf VApqc.gz
echo "unzip done"
find VApqc.gz -delete
